create extension if not exists btree_gist;

create type public.garage_status as enum ('draft', 'active', 'paused', 'inactive');
create type public.pricing_mode as enum ('hour', 'daily', 'period', 'monthly');
create type public.reservation_status as enum (
  'pending_payment',
  'confirmed',
  'active',
  'completed',
  'cancelled_by_driver',
  'cancelled_by_host',
  'payment_failed',
  'expired',
  'refunded',
  'disputed'
);
create type public.availability_kind as enum ('recurring', 'blocked');

create table if not exists public.profiles (
  id uuid primary key,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade
);
grant select, insert, update, delete on public.profiles to authenticated;
grant all on public.profiles to service_role;
alter table public.profiles enable row level security;
drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile" on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null,
  created_at timestamptz not null default now(),
  constraint user_roles_user_id_role_key unique (user_id, role),
  constraint user_roles_role_check check (role in ('admin'))
);
grant select, insert, update, delete on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
alter table public.user_roles enable row level security;
drop policy if exists "Users can view their own roles" on public.user_roles;
create policy "Users can view their own roles" on public.user_roles for select to authenticated using (auth.uid() = user_id);

create or replace function public.has_role(_user_id uuid, _role text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = _user_id and role = _role
  );
$$;

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  plate text not null,
  make text,
  model text not null,
  color text,
  vehicle_type text not null default 'car',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicles_plate_not_blank check (length(trim(plate)) > 0),
  constraint vehicles_model_not_blank check (length(trim(model)) > 0),
  constraint vehicles_owner_plate_key unique (owner_id, plate)
);
grant select, insert, update, delete on public.vehicles to authenticated;
grant all on public.vehicles to service_role;
alter table public.vehicles enable row level security;
drop policy if exists "Users can manage their own vehicles" on public.vehicles;
create policy "Users can manage their own vehicles" on public.vehicles for all to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create table if not exists public.garages (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete restrict,
  title text not null,
  description text,
  status public.garage_status not null default 'draft',
  address_label text not null,
  private_address text not null,
  private_access_instructions text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  capacity integer not null default 1,
  covered boolean not null default false,
  security_cameras boolean not null default false,
  gate_access boolean not null default false,
  max_vehicle_height_m numeric(4, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint garages_title_not_blank check (length(trim(title)) > 0),
  constraint garages_address_label_not_blank check (length(trim(address_label)) > 0),
  constraint garages_private_address_not_blank check (length(trim(private_address)) > 0),
  constraint garages_capacity_positive check (capacity > 0),
  constraint garages_latitude_range check (latitude is null or latitude between -90 and 90),
  constraint garages_longitude_range check (longitude is null or longitude between -180 and 180),
  constraint garages_max_vehicle_height_positive check (max_vehicle_height_m is null or max_vehicle_height_m > 0)
);
grant select, insert, update, delete on public.garages to authenticated;
grant all on public.garages to service_role;
alter table public.garages enable row level security;
drop policy if exists "Anyone authenticated can view active garage listings" on public.garages;
create policy "Anyone authenticated can view active garage listings" on public.garages for select to authenticated using (status = 'active' or auth.uid() = host_id);
drop policy if exists "Hosts can create garages" on public.garages;
create policy "Hosts can create garages" on public.garages for insert to authenticated with check (auth.uid() = host_id);
drop policy if exists "Hosts can update their own garages" on public.garages;
create policy "Hosts can update their own garages" on public.garages for update to authenticated using (auth.uid() = host_id) with check (auth.uid() = host_id);
drop policy if exists "Hosts can delete their own garages" on public.garages;
create policy "Hosts can delete their own garages" on public.garages for delete to authenticated using (auth.uid() = host_id);

create table if not exists public.garage_photos (
  id uuid primary key default gen_random_uuid(),
  garage_id uuid not null references public.garages(id) on delete cascade,
  storage_path text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  constraint garage_photos_storage_path_not_blank check (length(trim(storage_path)) > 0),
  constraint garage_photos_position_nonnegative check (position >= 0),
  constraint garage_photos_garage_position_key unique (garage_id, position)
);
grant select, insert, update, delete on public.garage_photos to authenticated;
grant all on public.garage_photos to service_role;
alter table public.garage_photos enable row level security;
drop policy if exists "Users can view photos for visible garages" on public.garage_photos;
create policy "Users can view photos for visible garages" on public.garage_photos for select to authenticated using (
  exists (
    select 1 from public.garages
    where garages.id = garage_photos.garage_id
      and (garages.status = 'active' or garages.host_id = auth.uid())
  )
);
drop policy if exists "Hosts can manage photos for their garages" on public.garage_photos;
create policy "Hosts can manage photos for their garages" on public.garage_photos for all to authenticated using (
  exists (select 1 from public.garages where garages.id = garage_photos.garage_id and garages.host_id = auth.uid())
) with check (
  exists (select 1 from public.garages where garages.id = garage_photos.garage_id and garages.host_id = auth.uid())
);

create table if not exists public.garage_pricing (
  id uuid primary key default gen_random_uuid(),
  garage_id uuid not null references public.garages(id) on delete cascade,
  mode public.pricing_mode not null,
  amount_cents integer not null,
  minimum_units integer not null default 1,
  maximum_units integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint garage_pricing_amount_positive check (amount_cents > 0),
  constraint garage_pricing_minimum_units_positive check (minimum_units > 0),
  constraint garage_pricing_maximum_units_valid check (maximum_units is null or maximum_units >= minimum_units),
  constraint garage_pricing_garage_mode_key unique (garage_id, mode)
);
grant select, insert, update, delete on public.garage_pricing to authenticated;
grant all on public.garage_pricing to service_role;
alter table public.garage_pricing enable row level security;
drop policy if exists "Users can view pricing for visible garages" on public.garage_pricing;
create policy "Users can view pricing for visible garages" on public.garage_pricing for select to authenticated using (
  exists (
    select 1 from public.garages
    where garages.id = garage_pricing.garage_id
      and (garages.status = 'active' or garages.host_id = auth.uid())
  )
);
drop policy if exists "Hosts can manage pricing for their garages" on public.garage_pricing;
create policy "Hosts can manage pricing for their garages" on public.garage_pricing for all to authenticated using (
  exists (select 1 from public.garages where garages.id = garage_pricing.garage_id and garages.host_id = auth.uid())
) with check (
  exists (select 1 from public.garages where garages.id = garage_pricing.garage_id and garages.host_id = auth.uid())
);

create table if not exists public.garage_availability (
  id uuid primary key default gen_random_uuid(),
  garage_id uuid not null references public.garages(id) on delete cascade,
  kind public.availability_kind not null,
  day_of_week smallint,
  start_time time,
  end_time time,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint garage_availability_day_of_week_range check (day_of_week is null or day_of_week between 0 and 6),
  constraint garage_availability_time_order check (start_time is null or end_time is null or end_time > start_time),
  constraint garage_availability_datetime_order check (starts_at is null or ends_at is null or ends_at > starts_at),
  constraint garage_availability_shape check (
    (kind = 'recurring' and day_of_week is not null and start_time is not null and end_time is not null and starts_at is null and ends_at is null)
    or
    (kind = 'blocked' and day_of_week is null and start_time is null and end_time is null and starts_at is not null and ends_at is not null)
  )
);
grant select, insert, update, delete on public.garage_availability to authenticated;
grant all on public.garage_availability to service_role;
alter table public.garage_availability enable row level security;
drop policy if exists "Users can view availability for visible garages" on public.garage_availability;
create policy "Users can view availability for visible garages" on public.garage_availability for select to authenticated using (
  exists (
    select 1 from public.garages
    where garages.id = garage_availability.garage_id
      and (garages.status = 'active' or garages.host_id = auth.uid())
  )
);
drop policy if exists "Hosts can manage availability for their garages" on public.garage_availability;
create policy "Hosts can manage availability for their garages" on public.garage_availability for all to authenticated using (
  exists (select 1 from public.garages where garages.id = garage_availability.garage_id and garages.host_id = auth.uid())
) with check (
  exists (select 1 from public.garages where garages.id = garage_availability.garage_id and garages.host_id = auth.uid())
);

create table if not exists public.instant_availability (
  id uuid primary key default gen_random_uuid(),
  garage_id uuid not null references public.garages(id) on delete cascade,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instant_availability_datetime_order check (ends_at > starts_at)
);
grant select, insert, update, delete on public.instant_availability to authenticated;
grant all on public.instant_availability to service_role;
alter table public.instant_availability enable row level security;
drop policy if exists "Users can view current instant availability" on public.instant_availability;
create policy "Users can view current instant availability" on public.instant_availability for select to authenticated using (
  ends_at > now()
  and exists (select 1 from public.garages where garages.id = instant_availability.garage_id and garages.status = 'active')
);
drop policy if exists "Hosts can manage instant availability for their garages" on public.instant_availability;
create policy "Hosts can manage instant availability for their garages" on public.instant_availability for all to authenticated using (
  exists (select 1 from public.garages where garages.id = instant_availability.garage_id and garages.host_id = auth.uid())
) with check (
  exists (select 1 from public.garages where garages.id = instant_availability.garage_id and garages.host_id = auth.uid())
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  garage_id uuid not null references public.garages(id) on delete restrict,
  driver_id uuid not null references public.profiles(id) on delete restrict,
  vehicle_id uuid not null references public.vehicles(id) on delete restrict,
  pricing_mode public.pricing_mode not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status public.reservation_status not null default 'pending_payment',
  garage_amount_cents integer not null,
  platform_fee_cents integer not null default 0,
  total_amount_cents integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservations_datetime_order check (ends_at > starts_at),
  constraint reservations_garage_amount_nonnegative check (garage_amount_cents >= 0),
  constraint reservations_platform_fee_nonnegative check (platform_fee_cents >= 0),
  constraint reservations_total_amount_valid check (total_amount_cents = garage_amount_cents + platform_fee_cents),
  constraint reservations_driver_is_vehicle_owner check (
    driver_id = (select owner_id from public.vehicles where vehicles.id = vehicle_id)
  )
);
grant select, insert, update, delete on public.reservations to authenticated;
grant all on public.reservations to service_role;
alter table public.reservations enable row level security;
drop policy if exists "Drivers and hosts can view related reservations" on public.reservations;
create policy "Drivers and hosts can view related reservations" on public.reservations for select to authenticated using (
  auth.uid() = driver_id
  or exists (select 1 from public.garages where garages.id = reservations.garage_id and garages.host_id = auth.uid())
);
drop policy if exists "Drivers can create their own reservations" on public.reservations;
create policy "Drivers can create their own reservations" on public.reservations for insert to authenticated with check (
  auth.uid() = driver_id
  and exists (select 1 from public.vehicles where vehicles.id = vehicle_id and vehicles.owner_id = auth.uid())
  and exists (select 1 from public.garages where garages.id = garage_id and garages.status = 'active')
);
drop policy if exists "Drivers can cancel their pending reservations" on public.reservations;
create policy "Drivers can cancel their pending reservations" on public.reservations for update to authenticated using (auth.uid() = driver_id) with check (auth.uid() = driver_id);

alter table public.reservations
  drop constraint if exists reservations_no_overlapping_active_periods;
alter table public.reservations
  add constraint reservations_no_overlapping_active_periods
  exclude using gist (
    garage_id with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  )
  where (status in ('pending_payment', 'confirmed', 'active'));

create index if not exists garages_host_id_idx on public.garages(host_id);
create index if not exists garages_status_location_idx on public.garages(status, latitude, longitude);
create index if not exists vehicles_owner_id_idx on public.vehicles(owner_id);
create index if not exists garage_photos_garage_id_idx on public.garage_photos(garage_id);
create index if not exists garage_pricing_garage_id_idx on public.garage_pricing(garage_id);
create index if not exists garage_availability_garage_id_idx on public.garage_availability(garage_id);
create index if not exists garage_availability_blocked_period_idx on public.garage_availability(garage_id, starts_at, ends_at) where kind = 'blocked';
create index if not exists instant_availability_garage_period_idx on public.instant_availability(garage_id, starts_at, ends_at);
create index if not exists reservations_driver_id_idx on public.reservations(driver_id);
create index if not exists reservations_garage_status_period_idx on public.reservations(garage_id, status, starts_at, ends_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at before update on public.vehicles for each row execute procedure public.set_updated_at();
drop trigger if exists garages_set_updated_at on public.garages;
create trigger garages_set_updated_at before update on public.garages for each row execute procedure public.set_updated_at();
drop trigger if exists garage_pricing_set_updated_at on public.garage_pricing;
create trigger garage_pricing_set_updated_at before update on public.garage_pricing for each row execute procedure public.set_updated_at();
drop trigger if exists garage_availability_set_updated_at on public.garage_availability;
create trigger garage_availability_set_updated_at before update on public.garage_availability for each row execute procedure public.set_updated_at();
drop trigger if exists instant_availability_set_updated_at on public.instant_availability;
create trigger instant_availability_set_updated_at before update on public.instant_availability for each row execute procedure public.set_updated_at();
drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at before update on public.reservations for each row execute procedure public.set_updated_at();
